(ns hive-di.core
  "Config DI — declarative, typed, ADT-backed config resolution.

   Core API:
     defconfig     — declare a config type with typed fields
     env           — field sourced from environment variable
     literal       — field with constant value
     resolve-config — resolve fields to typed map (Result)

   Example:
     (defconfig MilvusConfig
       :host            (env \"MILVUS_HOST\" :default \"localhost\" :type :string)
       :port            (env \"MILVUS_PORT\" :default 19530 :type :int)
       :secure          (env \"MILVUS_SECURE\" :default false :type :bool)
       :collection-name (literal \"hive-mcp-memory\"))

     (resolve-MilvusConfig)
     ;; => {:ok {:host \"localhost\" :port 19530 :secure false
     ;;          :collection-name \"hive-mcp-memory\"}}

     (resolve-MilvusConfig {:host \"milvus.svc\" :port \"9091\"})
     ;; => {:ok {:host \"milvus.svc\" :port 9091 :secure false
     ;;          :collection-name \"hive-mcp-memory\"}}"
  (:require [hive-di.source :as source]
            [hive-di.resolve :as resolve]
            [hive-di.schema :as schema]
            [hive-dsl.adt :as adt]))

;; =============================================================================
;; Re-exports — convenience API
;; =============================================================================

(def env source/env)
(def literal source/literal)
(def resolve-config resolve/resolve-config)

;; =============================================================================
;; Field Spec → ADT Variant Schema
;; =============================================================================

(defn- type->predicate
  "Map a hive-di type keyword to a Clojure predicate for defadt schemas."
  [type-kw]
  (case type-kw
    :string  'string?
    :int     'integer?
    :double  'number?
    :bool    'boolean?
    :keyword 'keyword?
    :vec     'vector?
    :enum    'keyword?
    'any?))

(defn- fields->resolved-schema
  "Build the :config/resolved variant schema from field specs."
  [field-pairs]
  (into {}
        (map (fn [[field-kw spec]]
               [field-kw (type->predicate (:type spec))]))
        field-pairs))

;; =============================================================================
;; defconfig Macro
;; =============================================================================

(defmacro defconfig
  "Define a typed config with ADT backing, field registry, Malli schema,
   and resolver shorthand.

   Generates:
     1. <Name>          — ADT type var (config/resolved, config/unresolved, config/invalid)
     2. <Name>-fields   — field registry map
     3. <Name>-schema   — Malli schema (closed map)
     4. resolve-<Name>  — resolver fn (0/1/2 arity)

   Usage:
     (defconfig MyConfig
       :host (env \"HOST\" :default \"localhost\" :type :string)
       :port (env \"PORT\" :default 8080 :type :int))

     (resolve-MyConfig)                          ;; from env + defaults
     (resolve-MyConfig {:port \"9090\"})          ;; with overrides
     (resolve-MyConfig {} {:env-fn mock-env})    ;; with custom env-fn"
  [config-name & field-defs]
  (let [;; Parse field pairs: [:host (env ...) :port (env ...)]
        field-pairs (partition 2 field-defs)

        ;; Symbol names
        fields-sym   (symbol (str config-name "-fields"))
        schema-sym   (symbol (str config-name "-schema"))
        resolver-sym (symbol (str "resolve-" config-name))

        ;; Build field registry at macro-expansion time
        ;; (field specs are evaluated, not quoted)
        field-keys (mapv first field-pairs)]

    `(do
       ;; 1. Field registry — the source of truth
       (def ~fields-sym
         ~(str "Field registry for " config-name " config.")
         ~(into {}
                (map (fn [[k v]] [k v]))
                field-pairs))

       ;; 2. Config ADT — lifecycle variants
       (adt/defadt ~config-name
         ~(str "Config ADT for " config-name ". Auto-generated by defconfig.")
         [:config/resolved   ~(into {} (map (fn [k] [k 'any?]) field-keys))]
         [:config/unresolved {:fields ~'set? :partial ~'map?}]
         [:config/invalid    {:errors ~'vector? :partial ~'map?}])

       ;; 3. Malli schema
       (def ~schema-sym
         ~(str "Malli schema for resolved " config-name ".")
         (schema/fields->malli-schema ~fields-sym))

       ;; 4. Resolver shorthand
       (defn ~resolver-sym
         ~(str "Resolve " config-name " from environment + overrides.\n"
               "Returns Result: (ok resolved-map) or (err :config/resolution-failed {...})")
         ([]
          (resolve/resolve-config ~fields-sym))
         ([~'overrides]
          (resolve/resolve-config ~fields-sym ~'overrides))
         ([~'overrides ~'opts]
          (resolve/resolve-config ~fields-sym ~'overrides ~'opts))))))
